<#
  Builds the shared UniGate AmneziaWG 3.1 shim as an Android ARM64 AAR.

  The same Go package is used by the Windows/macOS command and Android's
  in-process VpnService integration. Run setup-android.ps1 first.
#>

[CmdletBinding()]
param(
  [string]$ToolRoot = (Join-Path $env:LOCALAPPDATA "unigate-android-tools")
)

$ErrorActionPreference = "Stop"
$projectRoot = (Resolve-Path (Join-Path $PSScriptRoot "..")).Path
$goExe = Join-Path $ToolRoot "go\bin\go.exe"
$goPath = Join-Path $ToolRoot "gopath"
$goBin = Join-Path $goPath "bin"
$sdkDir = Join-Path $ToolRoot "android-sdk"
$ndkDir = Join-Path $sdkDir "ndk\28.0.13004108"
$sourceDir = Join-Path $projectRoot "awg-shim"
$destination = Join-Path $projectRoot "src-tauri\gen\android\app\libs\awgshim.aar"
$tempRoot = [System.IO.Path]::GetFullPath((Join-Path $env:TEMP "unigate-awgshim-$([guid]::NewGuid().ToString('N'))"))
$systemTemp = [System.IO.Path]::GetFullPath($env:TEMP).TrimEnd('\') + '\'
if (-not $tempRoot.StartsWith($systemTemp, [System.StringComparison]::OrdinalIgnoreCase)) {
  throw "Unsafe temporary directory: $tempRoot"
}
$rawAar = Join-Path $tempRoot "awgshim.aar"
$rawAarZip = Join-Path $tempRoot "awgshim.zip"

if (-not (Test-Path -LiteralPath $goExe)) {
  throw "Go not found. Run scripts/setup-android.ps1 first."
}
if (-not (Test-Path -LiteralPath $ndkDir)) {
  throw "Android NDK not found. Run scripts/setup-android.ps1 first."
}

New-Item -ItemType Directory -Force -Path $goBin | Out-Null
$env:GOPATH = $goPath
$env:GOBIN = $goBin
$env:JAVA_HOME = Join-Path $ToolRoot "jdk-17"
$env:ANDROID_HOME = $sdkDir
$env:ANDROID_SDK_ROOT = $sdkDir
$env:ANDROID_NDK_HOME = $ndkDir
$env:NDK_HOME = $ndkDir
$env:Path = "$(Join-Path $ToolRoot 'go\bin');$goBin;$(Join-Path $env:JAVA_HOME 'bin');$env:Path"

if (-not (Test-Path -LiteralPath (Join-Path $goBin "gomobile.exe"))) {
  & $goExe install github.com/sagernet/gomobile/cmd/gomobile@v0.1.12
  if ($LASTEXITCODE -ne 0) { throw "Failed to install gomobile" }
}
if (-not (Test-Path -LiteralPath (Join-Path $goBin "gobind.exe"))) {
  & $goExe install github.com/sagernet/gomobile/cmd/gobind@v0.1.12
  if ($LASTEXITCODE -ne 0) { throw "Failed to install gobind" }
}

New-Item -ItemType Directory -Force -Path (Split-Path $destination) | Out-Null
New-Item -ItemType Directory -Force -Path $tempRoot | Out-Null
Push-Location $sourceDir
try {
  & (Join-Path $goBin "gomobile.exe") bind `
    -target=android/arm64 `
    -androidapi 24 `
    -javapkg com.unigate.app `
    -trimpath `
    -o $rawAar `
    .
  if ($LASTEXITCODE -ne 0) { throw "awg-shim Android AAR build failed" }
} finally {
  Pop-Location
}

# libbox.aar and awgshim.aar are generated by the same gomobile fork and both
# contain identical go.Seq support classes. Keep the libbox copy to avoid D8's
# duplicate-class error; the AWG binding uses that shared copy at runtime.
$aarDir = Join-Path $tempRoot "aar"
$classesDir = Join-Path $tempRoot "classes"
$classesZip = Join-Path $tempRoot "classes.zip"
Copy-Item -LiteralPath $rawAar -Destination $rawAarZip
Expand-Archive -LiteralPath $rawAarZip -DestinationPath $aarDir
Copy-Item -LiteralPath (Join-Path $aarDir "classes.jar") -Destination $classesZip
Expand-Archive -LiteralPath $classesZip -DestinationPath $classesDir
$duplicateGoClasses = Join-Path $classesDir "go"
if (Test-Path -LiteralPath $duplicateGoClasses) {
  Remove-Item -LiteralPath $duplicateGoClasses -Recurse -Force
}
$jar = Join-Path $env:JAVA_HOME "bin\jar.exe"
Remove-Item -LiteralPath (Join-Path $aarDir "classes.jar") -Force
& $jar cf (Join-Path $aarDir "classes.jar") -C $classesDir .
if ($LASTEXITCODE -ne 0) { throw "Failed to rebuild awgshim classes.jar" }
if (Test-Path -LiteralPath $destination) {
  Remove-Item -LiteralPath $destination -Force
}
& $jar cf $destination -C $aarDir .
if ($LASTEXITCODE -ne 0) { throw "Failed to package awgshim.aar" }
Remove-Item -LiteralPath $tempRoot -Recurse -Force

Write-Host "awg-shim Android AAR ready: $destination"
